# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/checkout.proto for package 'store'

require 'grpc'
require 'protos/checkout_pb'

module Store
  module Checkout
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'store.Checkout'

      rpc :process_payment, CheckoutRequest, CheckoutResponse
    end

    Stub = Service.rpc_stub_class
  end
end
