# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/checkout.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "store.CheckoutRequest" do
    repeated :product_id, :int32, 1
    optional :user_uid, :int32, 2
    optional :cart_total, :int32, 3
  end
  add_message "store.CheckoutResponse" do
    optional :cart_total, :int32, 1
    optional :discount_total, :int32, 2
    optional :paid_amount, :int32, 3
    optional :status, :enum, 4, "store.CheckoutStatus"
  end
  add_enum "store.CheckoutStatus" do
    value :SUCCESSFUL, 0
    value :DECLINED_BY_BANK, 1
    value :DECLINED_BY_SECUTIRY, 2
  end
end

module Store
  CheckoutRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("store.CheckoutRequest").msgclass
  CheckoutResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("store.CheckoutResponse").msgclass
  CheckoutStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("store.CheckoutStatus").enummodule
end
